# Generated by Django 2.2.5 on 2019-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupos_totales', models.IntegerField(default=0)),
                ('cupos_desayuno', models.IntegerField(default=0)),
                ('cupos_almuerzo', models.IntegerField(default=0)),
                ('cupos_cena', models.IntegerField(default=0)),
                ('cupos_disponibles', models.IntegerField(default=0)),
                ('cupos_vendidos', models.IntegerField(default=0, editable=False)),
                ('fecha_de_transaccion', models.DateField(auto_now_add=True)),
                ('reservas_no_redimidas', models.IntegerField(default=0)),
            ],
        ),
    ]
