# Generated by Django 2.2.5 on 2019-10-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_transaccion', models.IntegerField(choices=[(1, 'Recarga'), (2, 'Compra')], default=1)),
                ('codigo', models.CharField(max_length=11)),
                ('Valor_de_transaccion', models.IntegerField()),
                ('fecha_de_transaccion', models.DateTimeField(auto_now_add=True)),
                ('persona_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuarios.Usuario')),
            ],
        ),
    ]
