# Generated by Django 2.2.5 on 2019-10-29 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('cedula', models.CharField(max_length=12)),
                ('codigo', models.CharField(max_length=11)),
                ('programa', models.CharField(max_length=25)),
                ('uid', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('saldo', models.PositiveIntegerField(blank=True, default=0)),
                ('reserva_desayuno', models.BooleanField(default=False)),
                ('reserva_almuerzo', models.BooleanField(default=False)),
                ('reserva_cena', models.BooleanField(default=False)),
                ('sancion', models.BooleanField(default=False)),
                ('comida_consumida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('bio', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
